### ISSUE TITLE
Bug: Reaction roll button doesn't do anything.

### ISSUE THREAD

**Issue by PrinceOfIonia** [StefanLeng/gurps-categorized-sheet#11]
This has happened with any GCS sheet I've tried it with, so I won't include one, but let me know if you want one anyways.

Pressing the reaction roll button WILL remove all modifiers in the modifier bucket, so it is trying to roll I think, but nothing appears in the chat.

**Comment by StefanLeng** [comment]
Do you have a Roll Table for Reactions set up and its name configured in the modul settings? If not the button is not functional (I can't distribute the table for legal resons). It should not be rendered in this situation,  but due to a bug I just found, it is regardless.

If you have the table, I have to look for another bug. If not, I recomend to set it up, but I will also fix it, so that the button is hidden if not functional.
![grafik](https://github.com/user-attachments/assets/af5d68dd-10ef-4219-bad0-43ab61508eb2)

**Comment by PrinceOfIonia** [comment]
Ok, so I have added the table and the button will now roll the table. However it does not appear to be adding any modifiers from the modifier bucket to the roll, is this intended?

**Comment by StefanLeng** [comment]
For the roll table to use the mod bucket, you have to set its roll formula up like this:
![grafik](https://github.com/user-attachments/assets/92fc015d-8c9f-4e4a-8851-dca08adf001d)

**Comment by PrinceOfIonia** [comment]
Ok, sorry I was not aware of that. I'm not sure how I would've known though, perhaps you might want to put that on the front page. It works fine once I put in that roll formula.

**Comment by StefanLeng** [comment]
Yes, that is a bit obscure. Its standard GGA behavior (not added by this module), but I am not sure it is documented anywhere. Good ideas to add it to the documentation, I plan to write more about the configuration anyway,

**Comment by StefanLeng** [comment]
In 0.4.1 the button is replaced by a message if the table is not configured. I also added some explanation to the front page,
